# Generated by Django 3.0.2 on 2020-01-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20200120_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='class_group',
        ),
        migrations.AddField(
            model_name='class',
            name='tests',
            field=models.ManyToManyField(related_name='tests', to='User.Test'),
        ),
    ]
