# Generated by Django 3.0.2 on 2020-01-21 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20200120_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='img/')),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.Test')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.Student')),
            ],
        ),
    ]
