# Generated by Django 3.0.2 on 2020-01-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_submition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submition',
            new_name='Submission',
        ),
    ]
