# Generated by Django 3.0.2 on 2020-01-21 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20200121_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Test'),
        ),
    ]
